#!/bin/bash
if xinput list-props "SynPS/2 Synaptics TouchPad" | grep "Device Enabled.*:.*1" >/dev/null
then
  xinput disable "SynPS/2 Synaptics TouchPad"
  notify-send -u low -i mouse "Trackpad disabled"
else
  xinput enable "SynPS/2 Synaptics TouchPad"
  notify-send -u low -i mouse "Trackpad enabled"
fi
